"""
Bundle data/site-content.json into assets/js/site-content-data.js so pages
load it via a plain <script> tag instead of fetch() (fetch of local JSON is
blocked by CORS when a page is opened as a file:// URL with no server).

Run this after editing data/site-content.json:
    python tools/bundle_site_content.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC_PATH = ROOT / "data" / "site-content.json"
OUT_PATH = ROOT / "assets" / "js" / "site-content-data.js"


def main():
    data = json.loads(SRC_PATH.read_text(encoding="utf-8"))
    body = json.dumps(data, ensure_ascii=False, indent=2)
    js = (
        "// AUTO-GENERATED by tools/bundle_site_content.py — do not edit directly.\n"
        "// Edit data/site-content.json and re-run the script instead.\n"
        "window.SFW_SITE_CONTENT = " + body + ";\n"
    )
    OUT_PATH.write_text(js, encoding="utf-8")
    langs = list(data.get("meta", {}).get("languages", {}).keys())
    print(f"Bundled site-content.json ({', '.join(langs)}) -> {OUT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
